### ISSUE TITLE
Navbar Add 

### ISSUE THREAD

**Issue by karantec** [karantec/MemeGenerator#1]
Add a responsive Navbar at the header section

**Comment by AnshulGoyal589** [comment]
I would to contribute in this, under hactoberfest 2023, kindly assign it to me

**Comment by karantec** [comment]
Wait for today's night

**Comment by AnshulGoyal589** [comment]
Okay, I have also made the navbar, I will make PR tomorrow.
Please assign rest of the issues too to me.

**Comment by VishnuAmit** [comment]
@karantec . Please assign it to me. I can do it by today

**Comment by karantec** [comment]
You can fork and clone it and start working on it

**Comment by karantec** [comment]
> @karantec . Please assign it to me. I can do it by today

start working on it by making branch on it

**Comment by AnshulGoyal589** [comment]
@karantec I have already Navbar with dark and light time with improved css and responsive nature is also taken care of.
Please check PR

**Comment by karantec** [comment]
Okay

**Comment by karantec** [comment]
issue resolved
