### ISSUE TITLE
Responsive Error

### ISSUE THREAD

**Issue by karantec** [karantec/MemeGenerator#4]
Make it Responsive  on Mobile View 

![image](https://github.com/karantec/MemeGenerator/assets/103360966/b1a49972-579e-49aa-bb90-c860dcb8bd2e)

**Comment by madm234** [comment]
I can make it responsive.

**Comment by karantec** [comment]
okay

**Comment by harshsharma-11** [comment]
i am working on this

**Comment by madm234** [comment]
> i am working on this

I have completed this. You didn't even commented earlier and why are you coming now and saying you are working on this. Lol.

**Comment by harshsharma-11** [comment]
no worry if you have already completed ,bacause i don't see your pr from last week that's why i think you are  not working on this

**Comment by madm234** [comment]
> no worry if you have already completed ,bacause i don't see your pr from last week that's why i think you are not working on this

Actually I was waiting for karan. I had also contributed to his prior project where I generated pr and he was not responding. That's the only reason man.

**Comment by karantec** [comment]
Closed Issue  resolved
